### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

### ISSUE THREAD

**Issue by VGraupera** [hwchase17/chat-your-data#1]
hitting this error, created new miniconda environment with python 3.11 on m2 mac, looked online at how to fix swigfaiss_avx2 but didnt find good solution. any tips appreciated

(langchain) 2023/chat-your-data[master|✔] % python app.py

Traceback (most recent call last):
  File "/Users/vidalgraupera/code/2023/chat-your-data/app.py", line 7, in <module>
    vectorstore = pickle.load(f)
                  ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

**Comment by niranjansenthilkumar** [comment]
running into same issue on mac m1. seems to be a bunch of issues with faiss and the new mac m1 and m2 models.

found a workaround with making Faiss compatible outside the conda environment.

https://github.com/facebookresearch/faiss/issues/1773#issuecomment-1237908374

**Comment by gpww** [comment]
running into same issue on windows seriver 2019, created new conda environment with python 3.10:

(LangChain) D:\Code\LangChain\chat-your-data>python app.py
Traceback (most recent call last):
  File "D:\Code\LangChain\chat-your-data\app.py", line 10, in <module>
    vectorstore = pickle.load(f)
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

**Comment by siddhantdante** [comment]
this error occurs when you use a pickle file generated on a different CPU architecture which supports avx2. Try to generate your own pickle file

**Comment by juanmillans** [comment]
Hi siddhantdante I ran into the same error, how can I generate my own pickle file, given I am in a windows OS? , and based on what should i generate it?

**Comment by fowlert** [comment]
Had the same problem on a mini M2.  Fixed in by running "python ingest_data.py" to create a new pickle file.  
This step is covered in the blog post https://blog.langchain.dev/tutorial-chatgpt-over-your-data/ which I failed to read carefully enough.

**Comment by nicoduffy** [comment]
Had the same issue on Win11 home ed. 22h2. Followed what @fowlert did to fix it.
