### ISSUE TITLE
ImportError: cannot import name 'extract_pages' from 'pdfminer.high_level' 

### ISSUE THREAD

**Issue by AbubakrChan** [hwchase17/chat-your-data#22]
PS C:\Users\l\streamlit-google-oauth\chat-your-data> python ingest_data.py
Traceback (most recent call last):
  File "C:\Users\l\streamlit-google-oauth\chat-your-data\ingest_data.py", line 9, in <module>
    raw_documents = loader.load()
  File "C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\document_loaders\unstructured.py", line 71, in load    
    elements = self._get_elements()
  File "C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\document_loaders\unstructured.py", line 106, in _get_elements
    from unstructured.partition.auto import partition
  File "C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\unstructured\partition\auto.py", line 21, in <module>
    from unstructured.partition.image import partition_image
  File "C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\unstructured\partition\image.py", line 5, in <module>
    from unstructured.partition.pdf import partition_pdf_or_image
  File "C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\unstructured\partition\pdf.py", line 9, in <module>
    from pdfminer.high_level import extract_pages
ImportError: cannot import name 'extract_pages' from 'pdfminer.high_level' (C:\Users\l\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfminer\high_level.py)

**Comment by AbubakrChan** [comment]
help required.
