### ISSUE TITLE
langchain 0.0.259 broke this demo

### ISSUE THREAD

**Issue by pablovela5620** [hwchase17/chat-your-data#25]
I have no problem running this demo with 0.0.249 but with the most recent version (0.0.259 as of this issue) I get the following error
```
(curator) ➜  chat-your-data git:(master) python app.py 
/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/deeplake/util/check_latest_version.py:32: UserWarning: A newer version of deeplake (3.6.17) is available. It's recommended that you update to the latest version using `pip install -U deeplake`.
  warnings.warn(
/Users/pablovela/0Dev/work/chat-your-data/app.py:74: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  submit = gr.Button(value="Send", variant="secondary").style(
/Users/pablovela/0Dev/work/chat-your-data/app.py:74: GradioDeprecationWarning: Use `scale` in place of full_width in the constructor. scale=1 will make the button expand, whereas 0 will not.
  submit = gr.Button(value="Send", variant="secondary").style(
Exception in thread Thread-5 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5 (run)'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    _patch_loop(loop)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py:1018: RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception in thread Thread-6 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-6 (run)'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    _patch_loop(loop)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Exception in thread Thread-7 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-7 (run)'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    _patch_loop(loop)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Exception in thread Thread-8 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-8 (run)'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    _patch_loop(loop)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Exception in thread Thread-9 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-9 (run)'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    _patch_loop(loop)
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
Exception in thread Thread-10 (run):
Traceback (most recent call last):
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/Users/pablovela/miniforge3/envs/curator/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-10 (run)'.
```

**Comment by pablovela5620** [comment]
Looks like this had to do with deeplake vectorstore, removing that package and switching to chroma fixed things
